<a href="https://colab.research.google.com/github/MonuDS/Colab-test/blob/master/notebooks/Tensor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import torch

In [2]:
x=torch.tensor([1,2,3])
x

tensor([1, 2, 3])

In [5]:
y=torch.tensor([
    [1,2,3],
    [4,5,6],
    [7,8,9]
],dtype=torch.float)
y

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])

In [6]:
torch.ones(3,4,dtype=torch.int)

tensor([[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]], dtype=torch.int32)

In [8]:
torch.zeros(5,3,2,dtype=torch.float)

tensor([[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]])

In [9]:
z=torch.rand(3,4,2,dtype=torch.float)
z

tensor([[[0.2666, 0.6328],
         [0.0712, 0.2850],
         [0.6996, 0.3542],
         [0.9692, 0.8380]],

        [[0.5112, 0.7913],
         [0.4114, 0.8208],
         [0.2906, 0.6336],
         [0.8116, 0.2023]],

        [[0.6547, 0.3344],
         [0.2571, 0.5537],
         [0.1758, 0.0650],
         [0.9074, 0.9844]]])

In [10]:
print(y)
y[0]

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])


tensor([1., 2., 3.])

In [11]:
y[:, 1]

tensor([2., 5., 8.])

In [12]:
z[2,:,0]

tensor([0.6547, 0.2571, 0.1758, 0.9074])

In [13]:
y.size()

torch.Size([3, 3])

In [14]:
y.size()[0]

3

In [15]:
t=torch.rand(3,3)
t

tensor([[0.0630, 0.6892, 0.9619],
        [0.2561, 0.2487, 0.9152],
        [0.6757, 0.8249, 0.7072]])

In [16]:
y+t

tensor([[1.0630, 2.6892, 3.9619],
        [4.2561, 5.2487, 6.9152],
        [7.6757, 8.8249, 9.7072]])

In [17]:
y*t

tensor([[0.0630, 1.3784, 2.8858],
        [1.0244, 1.2434, 5.4912],
        [4.7299, 6.5993, 6.3647]])

In [18]:
y*3

tensor([[ 3.,  6.,  9.],
        [12., 15., 18.],
        [21., 24., 27.]])

In [19]:
print(y)

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])


In [20]:
y.reshape(1,9)

tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [21]:
y.reshape(-1,)

tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [22]:
torch.squeeze(y.reshape(1,9))

tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [23]:
y.sum()

tensor(45.)

In [24]:
y.sum(0)

tensor([12., 15., 18.])

In [25]:
torch.max(y)

tensor(9.)

In [26]:
values,indices=torch.max(y,0)
print(values)
print(indices)

tensor([7., 8., 9.])
tensor([2, 2, 2])


In [27]:
values,indices=torch.max(y,1)
print(values)
print(indices)

tensor([3., 6., 9.])
tensor([2, 2, 2])


In [28]:
y[0,0].item()

1.0

In [29]:
y.numpy()

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]], dtype=float32)

In [30]:
import numpy as np
a=np.array([[1,2],[3,4]])
b=torch.from_numpy(a)
b

tensor([[1, 2],
        [3, 4]])

In [31]:
a[0,0]=2
a

array([[2, 2],
       [3, 4]])

In [32]:
b

tensor([[2, 2],
        [3, 4]])